from __future__ import annotations

import re


STOP_EN = set(
    "the a an is are was were be been being have has had do does did will would shall "
    "should may might can could of in to for on with at by from as into about between "
    "through during before after above below and or but not no nor so if then that this "
    "these those it its he she they we you i my your his her our their me him us them".split()
)

STOP_RU = set(
    "и в не на с что как по это он она они мы вы я а но за то все его её их этот эта "
    "эти из к у так уже от при бы до который когда только или тоже ещё более".split()
)

STOP_KK = set(
    "және мен бұл сол үшін бойынша сияқты өте бар жоқ емес болып туралы қажет негізгі "
    "арқылы бірге дейін кейін немесе әрі тағы бірақ да де дерек мәлімет жүйе деңгей".split()
)

STOPWORDS = STOP_EN | STOP_RU | STOP_KK
GENERIC_TERMS = {
    "such",
    "type",
    "kind",
    "form",
    "sort",
    "other",
    "common",
    "include",
    "includes",
    "used",
    "provide",
    "provides",
    "process",
    "term",
    "service",
    "services",
    "product",
    "products",
    "түр",
    "нысан",
    "санат",
    "жалпы",
    "негізгі",
    "мысал",
    "қызмет",
    "услуга",
    "пример",
    "форма",
    "категория",
    "процесс",
}
SPLIT_CONNECTORS = {"and", "or", "и", "или", "және", "немесе"}
TOKEN_RE = re.compile(r"[^\W_]+", re.UNICODE)
UNIT_OR_TECH_TOKENS = {
    "kw",
    "mw",
    "gw",
    "kwh",
    "mwh",
    "gwh",
    "twh",
    "wh",
    "ah",
    "mah",
    "cm",
    "cm2",
    "cm3",
    "mm",
    "kv",
    "hz",
    "kg",
    "mg",
    "lb",
    "doi",
    "isbn",
    "issn",
    "pmid",
    "bmatrix",
    "latex",
    "fig",
    "table",
    "et",
    "al",
}
BAD_SINGLE_TOKENS = {
    "use",
    "used",
    "using",
    "include",
    "includes",
    "including",
    "provide",
    "provides",
    "allow",
    "allows",
    "make",
    "makes",
    "show",
    "shows",
    "occur",
    "occurs",
    "work",
    "works",
    "begin",
    "end",
    "also",
    "which",
    "usually",
    "many",
    "significant",
    "typically",
    "over",
    "major",
    "mostly",
    "often",
    "much",
    "several",
    "various",
    "high",
    "low",
    "new",
    "old",
    "good",
    "bad",
    "large",
    "small",
    "different",
    "same",
    "general",
    "specific",
    "important",
    "common",
    "main",
    "basic",
    "certain",
    "other",
    "another",
    "more",
    "less",
    "most",
    "least",
    "than",
    "түр",
    "нысан",
    "санат",
    "жалпы",
    "негізгі",
    "мысал",
    "қызмет",
    "бұл",
    "сол",
    "яғни",
    "демек",
    "также",
    "пример",
    "процесс",
    "категория",
}
BAD_TERM_PHRASES = {
    "том числе",
    "в том числе",
    "составляет около",
    "около",
    "включая",
    "соның ішінде",
    "кез келген",
    "атап айтқанда",
    "үшін",
    "арқылы",
}
FUNCTIONAL_TERMS_EN = {
    "for",
    "to",
    "from",
    "between",
    "after",
    "before",
    "during",
    "which",
    "when",
    "while",
    "because",
    "including",
    "such",
    "some",
    "many",
}
FUNCTIONAL_TERMS_RU = {
    "для",
    "между",
    "после",
    "до",
    "кроме",
    "того",
    "даже",
    "одна",
    "является",
    "составляет",
    "представляют",
    "через",
    "при",
}
FUNCTIONAL_TERMS_KK = {
    "үшін",
    "арқылы",
    "ретінде",
    "болып",
    "кезінде",
    "сияқты",
    "ететін",
    "және",
    "мен",
    "немесе",
}
KK_PARTICIPLE_SUFFIXES = (
    "ған",
    "ген",
    "қан",
    "кен",
    "атын",
    "етін",
    "йтын",
    "йтін",
    "ушы",
    "уші",
)
KK_VERBAL_TAILS = {"алу", "беру", "ету", "болу", "шығару", "жасау", "қою", "келу", "кету"}
NOISE_TERM_PATTERNS = [
    re.compile(r"^(?:doi|isbn|issn|pmid)\b", re.IGNORECASE),
    re.compile(r"^[a-z]{1,2}\d+[a-z0-9]*$", re.IGNORECASE),
    re.compile(r"^\d+[a-z]{1,3}$", re.IGNORECASE),
    re.compile(r".*\b(?:bmatrix|latex|arxiv)\b.*", re.IGNORECASE),
]

